/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'shopkeeper' : null };
export type Cart = Array<CartItem>;
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type Category = { 'healthBeauty' : null } |
  { 'grocery' : null } |
  { 'sportsOutdoors' : null } |
  { 'fashion' : null } |
  { 'homeGarden' : null } |
  { 'electronics' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : number,
  'shopId' : ShopId,
  'customer' : Principal,
  'platformCommission' : number,
  'timestamp' : Time,
  'items' : Cart,
}
export type OrderId = bigint;
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface PlatformStats {
  'totalCommissions' : number,
  'totalOrders' : bigint,
  'totalSales' : number,
  'totalShops' : bigint,
  'pendingTickets' : bigint,
}
export interface Product {
  'id' : ProductId,
  'shopId' : ShopId,
  'name' : string,
  'description' : string,
  'quantity' : bigint,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : number,
}
export type ProductId = string;
export interface ProductInput {
  'shopId' : ShopId,
  'name' : string,
  'description' : string,
  'quantity' : bigint,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : number,
}
export interface Shop {
  'id' : ShopId,
  'owner' : Principal,
  'name' : string,
  'isOpen' : boolean,
  'approved' : boolean,
  'location' : string,
}
export type ShopId = string;
export interface SupportTicket {
  'id' : SupportTicketId,
  'status' : TicketStatus,
  'customer' : Principal,
  'shopkeeper' : [] | [Principal],
  'timestamp' : Time,
  'issue' : string,
}
export type SupportTicketId = bigint;
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'shopId' : [] | [ShopId],
  'appRole' : AppRole,
  'name' : string,
  'location' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], ProductId>,
  'addToCart' : ActorMethod<[ProductId, bigint], boolean>,
  'approveShop' : ActorMethod<[ShopId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[], OrderId>,
  'createSupportTicket' : ActorMethod<[string], SupportTicketId>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAllTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProductsByLocation' : ActorMethod<[string], Array<Product>>,
  'getShopOrders' : ActorMethod<[ShopId], Array<Order>>,
  'getShops' : ActorMethod<[], Array<Shop>>,
  'getShopsByLocation' : ActorMethod<[string], Array<Shop>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerShop' : ActorMethod<[string, string], ShopId>,
  'requestReturn' : ActorMethod<[OrderId, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleShopStatus' : ActorMethod<[ShopId], boolean>,
  'updateCartItem' : ActorMethod<[ProductId, bigint], boolean>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], boolean>,
  'updateTicketStatus' : ActorMethod<[SupportTicketId, TicketStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];