/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ShopId = IDL.Text;
export const Category = IDL.Variant({
  'healthBeauty' : IDL.Null,
  'grocery' : IDL.Null,
  'sportsOutdoors' : IDL.Null,
  'fashion' : IDL.Null,
  'homeGarden' : IDL.Null,
  'electronics' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductInput = IDL.Record({
  'shopId' : ShopId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : IDL.Float64,
});
export const ProductId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const SupportTicketId = IDL.Nat;
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const SupportTicket = IDL.Record({
  'id' : SupportTicketId,
  'status' : TicketStatus,
  'customer' : IDL.Principal,
  'shopkeeper' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'issue' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'shopkeeper' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'shopId' : IDL.Opt(ShopId),
  'appRole' : AppRole,
  'name' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Vec(CartItem);
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'shopId' : ShopId,
  'customer' : IDL.Principal,
  'platformCommission' : IDL.Float64,
  'timestamp' : Time,
  'items' : Cart,
});
export const PlatformStats = IDL.Record({
  'totalCommissions' : IDL.Float64,
  'totalOrders' : IDL.Nat,
  'totalSales' : IDL.Float64,
  'totalShops' : IDL.Nat,
  'pendingTickets' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'shopId' : ShopId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : IDL.Float64,
});
export const Shop = IDL.Record({
  'id' : ShopId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'isOpen' : IDL.Bool,
  'approved' : IDL.Bool,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductInput], [ProductId], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
  'approveShop' : IDL.Func([ShopId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([], [OrderId], []),
  'createSupportTicket' : IDL.Func([IDL.Text], [SupportTicketId], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAllTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getShopOrders' : IDL.Func([ShopId], [IDL.Vec(Order)], ['query']),
  'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getShopsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerShop' : IDL.Func([IDL.Text, IDL.Text], [ShopId], []),
  'requestReturn' : IDL.Func([OrderId, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleShopStatus' : IDL.Func([ShopId], [IDL.Bool], []),
  'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
  'updateTicketStatus' : IDL.Func(
      [SupportTicketId, TicketStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ShopId = IDL.Text;
  const Category = IDL.Variant({
    'healthBeauty' : IDL.Null,
    'grocery' : IDL.Null,
    'sportsOutdoors' : IDL.Null,
    'fashion' : IDL.Null,
    'homeGarden' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductInput = IDL.Record({
    'shopId' : ShopId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : Category,
    'image' : ExternalBlob,
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const SupportTicketId = IDL.Nat;
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const SupportTicket = IDL.Record({
    'id' : SupportTicketId,
    'status' : TicketStatus,
    'customer' : IDL.Principal,
    'shopkeeper' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'issue' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'shopkeeper' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'shopId' : IDL.Opt(ShopId),
    'appRole' : AppRole,
    'name' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Vec(CartItem);
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'shopId' : ShopId,
    'customer' : IDL.Principal,
    'platformCommission' : IDL.Float64,
    'timestamp' : Time,
    'items' : Cart,
  });
  const PlatformStats = IDL.Record({
    'totalCommissions' : IDL.Float64,
    'totalOrders' : IDL.Nat,
    'totalSales' : IDL.Float64,
    'totalShops' : IDL.Nat,
    'pendingTickets' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'shopId' : ShopId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : Category,
    'image' : ExternalBlob,
    'price' : IDL.Float64,
  });
  const Shop = IDL.Record({
    'id' : ShopId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'isOpen' : IDL.Bool,
    'approved' : IDL.Bool,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductInput], [ProductId], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
    'approveShop' : IDL.Func([ShopId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([], [OrderId], []),
    'createSupportTicket' : IDL.Func([IDL.Text], [SupportTicketId], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAllTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getShopOrders' : IDL.Func([ShopId], [IDL.Vec(Order)], ['query']),
    'getShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getShopsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerShop' : IDL.Func([IDL.Text, IDL.Text], [ShopId], []),
    'requestReturn' : IDL.Func([OrderId, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleShopStatus' : IDL.Func([ShopId], [IDL.Bool], []),
    'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
    'updateTicketStatus' : IDL.Func(
        [SupportTicketId, TicketStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };